/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import service.FournisseurService;

/**
 *
 * @author dell
 */
public class Main extends javax.swing.JFrame {

    
    public Main() {
        initComponents();
        this.setTitle("Pharmacie");
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        FournisseurMenu = new javax.swing.JMenuItem();
        medicamentMenu = new javax.swing.JMenuItem();
        venteMenu = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        grapheMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Gestion Pharmacie");

        FournisseurMenu.setMnemonic('o');
        FournisseurMenu.setText("Fournisseur");
        FournisseurMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FournisseurMenuActionPerformed(evt);
            }
        });
        fileMenu.add(FournisseurMenu);

        medicamentMenu.setMnemonic('s');
        medicamentMenu.setText("Medicament");
        medicamentMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicamentMenuActionPerformed(evt);
            }
        });
        fileMenu.add(medicamentMenu);

        venteMenu.setMnemonic('a');
        venteMenu.setText("Vente");
        venteMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venteMenuActionPerformed(evt);
            }
        });
        fileMenu.add(venteMenu);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        grapheMenu.setMnemonic('e');
        grapheMenu.setText("Analyse");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("graphe");
        cutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutMenuItemActionPerformed(evt);
            }
        });
        grapheMenu.add(cutMenuItem);

        menuBar.add(grapheMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void FournisseurMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FournisseurMenuActionPerformed
        FournisseurForm fm=new FournisseurForm();
        desktopPane.add(fm);
        fm.setVisible(true);
    }//GEN-LAST:event_FournisseurMenuActionPerformed

    private void medicamentMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicamentMenuActionPerformed
        MedicamentForm mf=new MedicamentForm();
        desktopPane.add(mf);
        mf.setVisible(true);
    }//GEN-LAST:event_medicamentMenuActionPerformed

    private void venteMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venteMenuActionPerformed
        VenteForm vf=new VenteForm();
        desktopPane.add(vf);
        vf.setVisible(true);
    }//GEN-LAST:event_venteMenuActionPerformed

    private void cutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutMenuItemActionPerformed
        GrapheFrame gf=new GrapheFrame();
        desktopPane.add(gf);
        gf.setVisible(true);
    }//GEN-LAST:event_cutMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem FournisseurMenu;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu grapheMenu;
    private javax.swing.JMenuItem medicamentMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem venteMenu;
    // End of variables declaration//GEN-END:variables

}
