/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import entities.Fournisseur;
import entities.Medicament;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import service.FournisseurService;
import service.MedicamentService;

/**
 *
 * @author dell
 */
public class MedicamentForm extends javax.swing.JInternalFrame {

    MedicamentService ms=null;
    FournisseurService fs=null;
    DefaultTableModel model=null;
    static int id;
    public MedicamentForm() {
        initComponents();
        ms = new MedicamentService();
        fs=new FournisseurService();
        loadFournisseurs();
        model=  (DefaultTableModel) listMed.getModel();
        load();
        
    }
    public void load(){
        model.setRowCount(0);
        for(Medicament m : ms.findAll()){
            Fournisseur f=fs.findById(m.getIdFournisseur());
            model.addRow(new Object[]{
                m.getId(),
                m.getNom(),
                m.getFamille(),
                m.getPrix(),
                m.getStock(),
                f
            });
        }
    }
    private void vider() {
        nameTxt.setText("");
        familleTxt.setText("");
        prixDouble.setText("");
        stockInt.setText("");
        comboFournisseur.setSelectedIndex(-1);

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nameTxt = new javax.swing.JTextField();
        familleTxt = new javax.swing.JTextField();
        prixDouble = new javax.swing.JTextField();
        stockInt = new javax.swing.JTextField();
        comboFournisseur = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ajoutMed = new javax.swing.JButton();
        suppMed = new javax.swing.JButton();
        UpdateMed = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listMed = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(51, 153, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Informations des médicaments"));
        jPanel1.setToolTipText("");

        nameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxtActionPerformed(evt);
            }
        });

        familleTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                familleTxtActionPerformed(evt);
            }
        });

        stockInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockIntActionPerformed(evt);
            }
        });

        comboFournisseur.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboFournisseur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFournisseurActionPerformed(evt);
            }
        });

        jLabel1.setText("name:");

        jLabel2.setText("famille:");

        jLabel3.setText("Prix:");

        jLabel4.setText("stock:");

        jLabel5.setText("Fournisseur:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(stockInt, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                    .addComponent(familleTxt)
                    .addComponent(nameTxt)
                    .addComponent(prixDouble))
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(comboFournisseur, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(familleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboFournisseur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prixDouble, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stockInt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 0, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("buttons"));

        ajoutMed.setText("Ajouter");
        ajoutMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutMedActionPerformed(evt);
            }
        });

        suppMed.setText("Supprimer");
        suppMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppMedActionPerformed(evt);
            }
        });

        UpdateMed.setText("Modifier");
        UpdateMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateMedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(152, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(suppMed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ajoutMed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UpdateMed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(117, 117, 117))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(ajoutMed)
                .addGap(42, 42, 42)
                .addComponent(suppMed)
                .addGap(47, 47, 47)
                .addComponent(UpdateMed)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        listMed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "nom", "famille", "Prix", "quantite", "Fournisseur"
            }
        ));
        listMed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listMedMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listMed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 961, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxtActionPerformed

    private void familleTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_familleTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_familleTxtActionPerformed

    private void ajoutMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutMedActionPerformed
        String nom = nameTxt.getText();
        String famille = familleTxt.getText();
        double prix = Double.parseDouble(prixDouble.getText());
        int stock = Integer.parseInt(stockInt.getText());

        // Récupérer le fournisseur sélectionné
        Fournisseur selectedFournisseur = (Fournisseur) comboFournisseur.getSelectedItem();
        Integer idFournisseur = null;
        if (selectedFournisseur != null) {
            idFournisseur = selectedFournisseur.getId();
        } else {
            // gérer le cas où aucun fournisseur n'est sélectionné
            System.out.println("Veuillez sélectionner un fournisseur.");
            return;
        }

        Medicament medicament = new Medicament(nom, famille, prix, stock, idFournisseur);
        ms.create(medicament);
        load();
        vider();
    }//GEN-LAST:event_ajoutMedActionPerformed

    private void stockIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockIntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockIntActionPerformed

    private void comboFournisseurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFournisseurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboFournisseurActionPerformed

    private void listMedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listMedMouseClicked
        int selectedRow = listMed.getSelectedRow();

    if (selectedRow >= 0) {
        // Assuming columns: 0:id, 1:nom, 2:famille, 3:prix, 4:quantite, 5:fournisseur
        id = Integer.parseInt(listMed.getModel().getValueAt(selectedRow, 0).toString());
        String nom = listMed.getModel().getValueAt(selectedRow, 1).toString();
        String famille = listMed.getModel().getValueAt(selectedRow, 2).toString();
        String prix = listMed.getModel().getValueAt(selectedRow, 3).toString();
        String quantite = listMed.getModel().getValueAt(selectedRow, 4).toString();
        String fournisseurNameOrId = listMed.getModel().getValueAt(selectedRow, 5).toString();

        nameTxt.setText(nom);
        familleTxt.setText(famille);
        prixDouble.setText(prix);
        stockInt.setText(quantite);

        
    }
    }//GEN-LAST:event_listMedMouseClicked

    private void suppMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppMedActionPerformed
        int reponse=JOptionPane.showConfirmDialog(this, "voulez vous supprimer ce medicament ?");
        if(reponse==0){
            ms.delete(ms.findById(id));
            load();
            vider();
        }
    }//GEN-LAST:event_suppMedActionPerformed

    private void UpdateMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateMedActionPerformed
            int reponse = JOptionPane.showConfirmDialog(this, "Voulez-vous modifier ce médicament ?");
            if (reponse == JOptionPane.YES_OPTION) {  // or == 0, but YES_OPTION is clearer

                try {
                    // Récupérer les valeurs du formulaire
                    double prix = Double.parseDouble(prixDouble.getText());
                    int stock = Integer.parseInt(stockInt.getText());
                    Fournisseur selectedFournisseur = (Fournisseur) comboFournisseur.getSelectedItem();
                    if (selectedFournisseur == null) {
                        JOptionPane.showMessageDialog(this, "Veuillez sélectionner un fournisseur.", "Erreur", JOptionPane.ERROR_MESSAGE);
                        return;
                    }

                    Medicament medicament = new Medicament(
                        id,                           // il faut que tu conserves cet id (champ global ou autre)
                        nameTxt.getText(),
                        familleTxt.getText(),
                        prix,
                        stock,
                        selectedFournisseur.getId()
                    );

                    ms.update(medicament);  // appel à ta méthode update dans MedicamentService

                    load();   // recharge la liste/tableau des médicaments
                    vider();  // vide le formulaire

                    JOptionPane.showMessageDialog(this, "Médicament modifié avec succès.");

                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Prix ou stock invalide.", "Erreur", JOptionPane.ERROR_MESSAGE);
                }
            }
    }//GEN-LAST:event_UpdateMedActionPerformed
    public void loadFournisseurs() {
        List<Fournisseur> fournisseurs = fs.findAll();
        comboFournisseur.removeAllItems();
        for (Fournisseur f : fournisseurs) {
            comboFournisseur.addItem(f);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton UpdateMed;
    private javax.swing.JButton ajoutMed;
    private javax.swing.JComboBox comboFournisseur;
    private javax.swing.JTextField familleTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listMed;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JTextField prixDouble;
    private javax.swing.JTextField stockInt;
    private javax.swing.JButton suppMed;
    // End of variables declaration//GEN-END:variables
}
