/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import entities.Medicament;
import entities.Vente;
import java.sql.Date;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import service.MedicamentService;
import service.VenteService;

/**
 *
 * @author dell
 */
public class VenteForm extends javax.swing.JInternalFrame {
    VenteService vs=null;
    MedicamentService ms=null;
    DefaultTableModel model=null;
    static int idVente;
    
    public VenteForm() {
        initComponents();
        ms = new MedicamentService();
        loadMedicaments();
        vs=new VenteService();
        model=  (DefaultTableModel) listVente.getModel();
        load();
    }
    private void vider() {
        quantiteTxt.setText("");
        comboMedicament.setSelectedIndex(-1);
        dateVente.setDate(null);
    }
    public void load() {
        model.setRowCount(0);

        for (Vente v : vs.findAll()) {
            Medicament m = ms.findById(v.getIdMedicament());
            model.addRow(new Object[] {
                v.getId(),
                m,   // or medicament name (see below)
                v.getDateVente(),
                v.getQuantite()
            });
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        comboMedicament = new javax.swing.JComboBox();
        quantiteTxt = new javax.swing.JTextField();
        dateVente = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        addVente = new javax.swing.JButton();
        suppVente = new javax.swing.JButton();
        updateVente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listVente = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(51, 153, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ventes"));

        comboMedicament.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboMedicament.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMedicamentActionPerformed(evt);
            }
        });

        jLabel1.setText("Medicament:");

        jLabel2.setText("Quantitee vendue:");

        jLabel3.setText("Date de vente:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quantiteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboMedicament, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateVente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboMedicament, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateVente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantiteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 0, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Buttons"));

        addVente.setText("Ajouter");
        addVente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVenteActionPerformed(evt);
            }
        });

        suppVente.setText("Supprimer");
        suppVente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppVenteActionPerformed(evt);
            }
        });

        updateVente.setText("Modifier");
        updateVente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateVenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(suppVente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addVente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateVente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(116, 116, 116))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(addVente)
                .addGap(43, 43, 43)
                .addComponent(suppVente)
                .addGap(45, 45, 45)
                .addComponent(updateVente)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        listVente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Medicament", "dateVente", "quantitee vendue"
            }
        ));
        listVente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listVenteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listVente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 851, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboMedicamentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMedicamentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboMedicamentActionPerformed

    private void addVenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVenteActionPerformed
        Medicament selectedMedicament = (Medicament) comboMedicament.getSelectedItem();
        Integer idMedicament = null;
        if (selectedMedicament != null) {
            idMedicament = selectedMedicament.getId();
        } else {
            // gérer le cas où aucun fournisseur n'est sélectionné
            System.out.println("Veuillez sélectionner un Medicament.");
            return;
        }
        int quantite = Integer.parseInt(quantiteTxt.getText());
        java.util.Date utilDate = dateVente.getDate();
        if (utilDate == null) {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner une date.");
            return;
        }

        // Convert to LocalDate
        LocalDate dateVente = utilDate.toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalDate();

        Vente v = new Vente(idMedicament, dateVente, quantite);
        vs.create(v);
        vider();
        load();
    }//GEN-LAST:event_addVenteActionPerformed

    private void listVenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listVenteMouseClicked
        int selectedRow = listVente.getSelectedRow();

        if (selectedRow >= 0) {

            // ID vente
            idVente = Integer.parseInt(
                listVente.getModel().getValueAt(selectedRow, 0).toString()
            );

            // Medicament object
            Medicament m = (Medicament) listVente.getModel().getValueAt(selectedRow, 1);

            // Date vente (LocalDate)
            LocalDate venteDate = (LocalDate) listVente.getModel().getValueAt(selectedRow, 2);

            // Quantité
            int quantite = Integer.parseInt(
                listVente.getModel().getValueAt(selectedRow, 3).toString()
            );

            // Fill form
            comboMedicament.setSelectedItem(m);
            quantiteTxt.setText(String.valueOf(quantite));

            // Convert LocalDate → java.util.Date for JDateChooser
            java.util.Date utilDate = java.sql.Date.valueOf(venteDate);
            dateVente.setDate(utilDate);  
        }

    }//GEN-LAST:event_listVenteMouseClicked

    private void suppVenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppVenteActionPerformed
        int reponse=JOptionPane.showConfirmDialog(this, "voulez vous supprimer ce Vente ?");
        if(reponse==0){
            vs.delete(vs.findById(idVente));
            load();
            vider();
        }
    }//GEN-LAST:event_suppVenteActionPerformed

    private void updateVenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateVenteActionPerformed
        int reponse = JOptionPane.showConfirmDialog(this, "Voulez-vous modifier cette vente ?");
        if (reponse == JOptionPane.YES_OPTION) {

            try {
                // Medicament selected
                Medicament selectedMed = (Medicament) comboMedicament.getSelectedItem();
                if (selectedMed == null) {
                    JOptionPane.showMessageDialog(this, "Veuillez sélectionner un médicament.", "Erreur", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                int idMedicament = selectedMed.getId();

                // Quantité
                int quantite = Integer.parseInt(quantiteTxt.getText());

                // Date (JDateChooser -> LocalDate)
                java.util.Date utilDate = dateVente.getDate();
                if (utilDate == null) {
                    JOptionPane.showMessageDialog(this, "Veuillez sélectionner une date de vente.", "Erreur", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                LocalDate dateVente = utilDate.toInstant()
                        .atZone(ZoneId.systemDefault())
                        .toLocalDate();

                // Create Vente object (with ID!)
                Vente v = new Vente();
                v.setId(idVente);
                v.setIdMedicament(idMedicament);
                v.setDateVente(dateVente);
                v.setQuantite(quantite);

                vs.update(v);   // <-- you need this method in VenteService/DAO

                load();   // reload vente table
                vider();  // clear fields

                JOptionPane.showMessageDialog(this, "Vente modifiée avec succès.");

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Quantité invalide.", "Erreur", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_updateVenteActionPerformed
    public void loadMedicaments() {
    List<Medicament> medicaments = ms.findAll();
    comboMedicament.removeAllItems();

    for (Medicament m : medicaments) {
        comboMedicament.addItem(m);
    }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addVente;
    private javax.swing.JComboBox comboMedicament;
    private com.toedter.calendar.JDateChooser dateVente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listVente;
    private javax.swing.JTextField quantiteTxt;
    private javax.swing.JButton suppVente;
    private javax.swing.JButton updateVente;
    // End of variables declaration//GEN-END:variables
}
